# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "pathways-job.controller.labels" . | nindent 4 }}
  name: {{ include "pathways-job.controller.deployment.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas:  {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      {{- include "pathways-job.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        pathways-job.x-k8s.io/config-hash: {{ include (print $.Template.BasePath "/manager/configmap.yaml") . | sha256sum }}
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "pathways-job.controller.labels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /manager
        args:
          - --metrics-bind-address=:8443
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- with .Values.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        name: manager
        {{- with .Values.manager.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.manager.resources | nindent 10 }}
      securityContext:
        {{- toYaml .Values.manager.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "pathways-job.controller.serviceAccount.name" . }}
      terminationGracePeriodSeconds: 10
